# ==============================================================
# Configuração de Conexão com o Banco de Dados na Nuvem (Render)
# ==============================================================
spring.datasource.url=jdbc:postgresql://dpg-d6nf6qv5gffc73c2d690-a.oregon-postgres.render.com/minirpg_db?sslmode=require
spring.datasource.username=minirpg_db_user
spring.datasource.password=9Ck6z1ADrOXh5k9uaq6Yqz8rhPv3xCJW

# ==============================================================
# Configurações do Hibernate/JPA
# ==============================================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect