CREATE TABLE distribuidora (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               nome VARCHAR(500) NOT NULL,
                               sigla VARCHAR(500) NOT NULL,
                               estado VARCHAR(500) NOT NULL
);

CREATE TABLE obra (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      descricao VARCHAR(500) NOT NULL,
                      data_inicio DATE NOT NULL,
                      data_fim DATE NOT NULL,
                      custo_total NUMERIC(19, 2) NOT NULL,
                      distribuidora_id BIGINT NOT NULL,
                      CONSTRAINT fk_obra_distribuidora FOREIGN KEY (distribuidora_id) REFERENCES distribuidora(id)
);

CREATE TABLE itens_custo (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             descricao VARCHAR(100) NOT NULL,
                             valor NUMERIC(19, 2) NOT NULL,
                             tipo_custo VARCHAR(50) NOT NULL,
                             obra_id BIGINT NOT NULL,
                             CONSTRAINT fk_item_obra FOREIGN KEY (obra_id) REFERENCES obra(id)
);